### ISSUE TITLE
Does not log exception when using DrainingControl

### ISSUE THREAD

**Issue by ayoung** [akkadotnet/Akka.Streams.Kafka#129] opened 2020-04-30 07:19 UTC
When using `KafkaConsumer.SourceWithOffsetContext` with `DrainingControl` and an exception is thrown within a flow, nothing gets logged making it very difficult to debug what actually occurred. Here's the sample app that will demonstrate this.

```c#
using System;
using Akka;
using Akka.Actor;
using Akka.Configuration;
using Akka.Streams;
using Akka.Streams.Dsl;
using Akka.Streams.Kafka.Dsl;
using Akka.Streams.Kafka.Helpers;
using Akka.Streams.Kafka.Settings;
using Akka.Util.Internal;
using Confluent.Kafka;
using Serilog;

namespace StreamsDoesntLog
{
    class Program
    {
        static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.Console()
                .CreateLogger();

            var actorSystemConfig =
                ConfigurationFactory.ParseString(@"
                        akka.loglevel=DEBUG
                        akka.loggers=[""Akka.Logger.Serilog.SerilogLogger, Akka.Logger.Serilog""]
                        ")
                    .WithFallback(ConfigurationFactory.FromResource<ConsumerSettings<object, object>>(
                        "Akka.Streams.Kafka.reference.conf"));

            using var system = ActorSystem.Create("system", actorSystemConfig);
            using var materializer = system.Materializer();

            var consumerConfig = new ConsumerConfig
            {
                EnableAutoCommit = true,
                EnableAutoOffsetStore = false,
                AutoOffsetReset = AutoOffsetReset.Earliest
            };

            var consumerSettings = ConsumerSettings<Byte[], Byte[]>.Create(system, Deserializers.ByteArray, Deserializers.ByteArray)
                .WithBootstrapServers("localhost:9092")
                .WithStopTimeout(TimeSpan.Zero)
                .WithGroupId("group1");

            consumerConfig.ForEach(kv => consumerSettings = consumerSettings.WithProperty(kv.Key, kv.Value));

            var committerSettings = new CommitterSettings(10, TimeSpan.FromSeconds(10), 2);

            KafkaConsumer.SourceWithOffsetContext(consumerSettings,
                    Subscriptions.Topics("events-topic"))
                .Select(result =>
                {
                    throw new Exception("won't get logged");
                    return "don't return";
                })
                .AsSource()
                .ToMaterialized(
                    Committer.SinkWithOffsetContext<string>(committerSettings),
                    Keep.Both)
                .MapMaterializedValue(t1 =>
                    DrainingControl<NotUsed>.Create(t1.Item1, t1.Item2.ContinueWith(t2 => NotUsed.Instance)))
                .Run(materializer).IsShutdown.Wait();
        }
    }
}
```

**Comment by ayoung** [comment] 2020-05-06 00:32
Ok. I figured out that the exception is made available in `t1.Item2` if I do this.

```c#
.MapMaterializedValue(t1 =>
    DrainingControl<NotUsed>.Create(t1.Item1, t1.Item2.ContinueWith(t2 =>
    {
        // Exceptions in the stream show up here. If you don't catch it here, it gets swallowed up
        if (t2.Exception != null)
        {
            _logger.Fatal(t2.Exception, "Stream shutdown unexpectedly");
        }

        return NotUsed.Instance;
    })));
```

Is this the right way to handle an exception?

**Comment by IgorFedchenko** [comment] 2020-05-12 12:07
@ayoung Well, in your sample, before using `DrainingControl` you have a source, that is materialized into pair `(IControl, Task<NotUsed>)`. Probably we should add tuple items naming here to simplify understanding, but it is actually `(IControl Control, Task<NotUsed> StreamCompletion)`. So, to create `DrainingControl`, you are passing there special object to contol the stream execution (`IControl`) and the stream task.

Then, you were using `IsShutdown.Wait()` which was just starting separate "shutdown" task, and you were waiting for it's completion. And it was completed without issues. It is just a special task that is representing asynchronous shutdown process. When `IsShutdown` is completed, you may be safe that source will not produce elements anymore.

Instead, you would better use  `StreamCompletion.Wait()` - that is, wait for stream to complete it's internal task, processing task. It is not the same as `IsShutdown` task, because after stopping the source it may still take some time to stop internal actors and processing. 

So, if you need to check what's up with source processing task, `StreamCompletion` property is what you need.

**Comment by IgorFedchenko** [comment] 2020-05-12 12:08
I guess we may close this issue, since by design you are getting `Task` object that you are able to ignore, or log exceptions - whatever you want.

**Closed by IgorFedchenko** 2020-05-12 12:08 UTC

**Comment by ayoung** [comment] 2020-05-12 21:59
I changed it to use `StreamCompletion.Wait()` but it still does not expose the exception within `StreamCompletion.Exception`. i.e. that property is `null`.

**Comment by IgorFedchenko** [comment] 2020-08-20 14:01
@ayoung Ah, yeah, actually in the sample above `StreamCompletion` task will not throw because we are ignoring consuming exception in continuation.

So, while your way of handing exception in the second comment works (if you just need to log it and then ignore), here is how you can pass exception to outside of the stream:

```c#
KafkaConsumer.SourceWithOffsetContext(consumerSettings, Subscriptions.Topics("events-topic"))
	.Select(result =>
	{
		throw new Exception("won't get logged");
		return "don't return";
	})
	.AsSource()
	.ToMaterialized(
		Committer.SinkWithOffsetContext<string>(committerSettings),
		Keep.Both)
	.MapMaterializedValue(t1 =>
		DrainingControl<NotUsed>.Create(t1.Item1, t1.Item2.ContinueWith(t2 =>
		{
			// If consuming actually failed - we will re-throw it's failure exception
			if (t2.Exception != null)
				throw t2.Exception;
			
			return NotUsed.Instance;
		})))
	.Run(materializer).StreamCompletion.Wait(); // Throws AggregateException
```

So the idea is that `DrainingControl.SteamCompletion` contains the actual execution task, passed in `t1.Item2`.  And you can either handle exception in task continuation (as you did), or just let it pass in "Failed" state in `StreamCompletion` property and handle it from outside of the stream.
