### ISSUE TITLE
Akka Stream is consuming slow

### ISSUE THREAD

**Issue by jsb81** [akkadotnet/Akka.Streams.Kafka#209] opened 2021-05-26 05:38 UTC
We have a simple flow like this:

```
_control = KafkaConsumer.CommittableSource(consumerSettings, Subscriptions.Topics(sourceTopics)))
        .SelectAsync(15, msg => Parser(msg, _consumer.ConfigurationTopic))
        .Via(KafkaProducer.FlexiFlow<string, byte[], ICommittable>(producerSettings))
        .Select(m => m.PassThrough)
        .ToMaterialized(Committer.Sink(committerSettings), Keep.Both)
        .MapMaterializedValue(DrainingControl<NotUsed>.Create)
        .Run(_materializer);
```

we started testing our application but almost immediately we discovered that is consuming very slow (something like 50 messages per second). We tried to reimplement our flow without Akka, using native KafkaConsumerBuilder and after that change messages are consumed many times faster.

ConsumerConfig:
```
    AutoOffsetReset = AutoOffsetReset.Earliest,
    EnableAutoCommit = false,
```

ProducerConfig:
```
    LingerMs = 10,
    Acks = Acks.All,
    MaxInFlight = 1,
    MessageSendMaxRetries = int.MaxValue,
```

Any suggestions?

**Comment by IgorFedchenko** [comment] 2021-05-27 14:56
@jsb81 Hmm, the setup looks good to me.

I think that would need some more debugging/measuring. If that is possible, could you provide some measures/times (i.e. via `Stopwatch`) tracked on each step (or logs that show when each message received by consumer, then handled by FlexiFlow, then committed)? And need to compare those logs with the ones that native Confluent driver gives. So that we would take a closer look on some particular part of the flow.

From out of my head, `KafkaProducer` and `Committer` are quite simple stages that should not give much delays, so I am wondering if that's a `KafkaConsumer` who is really slowing down processing here.

**Comment by hannesstockner** [comment] 2021-05-27 17:31
It's definitely the KafkaConsumer stage. We changed the flow as follow:

`KafkaConsumer.PlainSource(consumerSettings, Subscriptions.Topics(sourceTopics))
        .Select(msg => msg)
        .RunWith(Sink.Ignore<IEnvelope<string, byte[], NotUsed>>(), _materializer);`

And we can see:
- Consuming around 50msg/sec
- it consumes a set of messages, then for ~2sec nothing happens, then again it consumes a set of messages

With the Confluent driver its a constant incoming stream of data, without any breaks and much more messages a sec ~1k+.

**Comment by IgorFedchenko** [comment] 2021-05-27 22:18
@hannesstockner @jsb81 You know what you can start with: internal consuming actor has a "tick message" he is sending to himself in order to call `_consumer.Consume` from Confluent driver. The default interval for this "tick" is 50ms (`akka.kafka.consumer.poll-interval` in settings). 

What if you will set `consumerSettings.WithPollInterval(TimeSpan interval)` to something like `10ms` or even `1ms`? That would be the first thing I would check.

**Comment by jsb81** [comment] 2021-05-31 08:14
@IgorFedchenko we discovered that this problem could be related to kafka partition balancing. On our source topic we have 32 partitions but we observed that when using Akka Streams it is not balancing, it always use the same partition, this does not happen using native kafka consumer. We also discovered that consuming from a topic with one parition our flow becomes fast.

**Comment by IgorFedchenko** [comment] 2021-05-31 20:03
@jsb81 
> it always use the same partition, this does not happen using native kafka consumer

So does this mean that Akka.Streams.Kafka flow consumes only one (or few) partition, and does not consume messages from other partitions at all? It is not balancing - you mean that when consumer connects to topic, it is consuming messages from only some of the partitions, not from all of them?

Because if so, consuming is not slow - consuming does not consume some messages at all. Right? I.e. if message A went to partition 0, then B to partition 1, then C to partition 3. and Akka.Streams.Kafka consumer does not rebalance properly and consumes only partitions 0 and 1 - then it will never receive message C. Is that what you see in your case? Or you receive all A B C messages, but it is happening slower then via native kafka driver?

Because if the consuming is slow, then `poll-interval` is something we need to try first. If our consumer just does not consume from some partitions at all - that definitely sounds like a clear bug in our consumer's code (while there is a test verifying that, probably it is missing something).

**Comment by jsb81** [comment] 2021-06-01 09:53
@IgorFedchenko In my previous I forgot to tell you answer that we tryed to change `poll-interval` but we do not obtained better performances. Moreover what we found is that performances are worst decreasing that parameter.

I do have other updates.

We have a source topic with 32 partitions and we did the following tests:

1. we changed our flow using `CommittablePartitionedSource` with separate streams per partition. This way kafka is balancing and flow is fast (~3000msg/sec).
2. we tryed to produce 1000 messages on each partition on our source topic to check what happens using the previous flow. Result is that it switches between partitions but it is super slow.
3. we tryed to run test (2) using `CommittablePartitionedSource` and again flow is fast and it switches between partitions.

**Comment by IgorFedchenko** [comment] 2021-06-04 20:32
I see. That is weird, and sounds like some problem with our implementation. I am wondering if that has to do with how we are handling partition assignment in `KafkaConsumerActor` code...

We are definitely going to fix this - but does this issue block you from using `Akka.Streams.Kafka` right now @jsb81 ? This sounds like something that will take time to investigate, so I am not sure how quickly we can fix that.

**Comment by jsb81** [comment] 2021-06-05 14:37
@IgorFedchenko Don't worry, no rush. In the meantime we reimplemented our flow using native confluent driver. Just let us know when there will be any update.

**Comment by Arkatufus** [comment] 2021-08-23 16:48
Part of the problem is mis-port of the code from JVM to C#. The underlying driver for Java and C# behaves completely differently so our code will have to deviate from the JVM code. Any optimization done in the JVM code must be checked to see if it actually applies in C#.

**Comment by Arkatufus** [comment] 2021-08-24 15:11
One of the difference I've found so far is that the JVM Kafka relies on the `Poll` method where it manually ask the Kafka server for messages, this includes system messages like commit status and partition changes. In C#, we don't have access to the `Poll` method inside the `librdkafka` native library, we can only use the `Consume` method.

These spells out a few differences:
- The JVM implementation have to constantly probe the Kafka server for changes, the C# implemention should not
- The JVM implementation have the luxury of asking the client for everything it has in its current buffer in a synchronous way (using `Poll(0)`), C# can only consume 1 message at a time asynchronously.
- Since C# can only consume 1 message at a time, we'd have to do a loop and retrieve as many messages as possible each time a poll timer is fired. This was the cause of the slow performance, will be addressed in a fix.

**Comment by Aaronontheweb** [comment] 2021-08-30 14:21
Resolved performance issues via https://github.com/akkadotnet/Akka.Streams.Kafka/pull/217

However, @Arkatufus is still working on investigating:

>  On our source topic we have 32 partitions but we observed that when using Akka Streams it is not balancing, it always use the same partition, this does not happen using native kafka consumer. We also discovered that consuming from a topic with one parition our flow becomes fast.

**Comment by Arkatufus** [comment] 2021-08-30 17:23
I did encouter partition assignment problems in my tests, but it was related to buggy code in either librdkafka or Confluent Kafka for .NET when message keys were set to null, which is __not__ the same case as this issue.

@jsb81, @hannesstockner, what do you use as key values? are there a lot of repeated keys in the message?

**Comment by Aaronontheweb** [comment] 2021-09-08 19:31
This is resolved in https://github.com/akkadotnet/Akka.Streams.Kafka/releases/tag/1.1.4

**Closed by Aaronontheweb** 2021-09-08 19:31 UTC
Labels: bug
